// Lists of common companies, universities, degrees, and fields of study

export const COMMON_COMPANIES = [
  "Google",
  "Microsoft",
  "Apple",
  "Amazon",
  "Meta",
  "Tesla",
  "Netflix",
  "Adobe",
  "Salesforce",
  "Oracle",
  "IBM",
  "Intel",
  "HP",
  "Dell",
  "Cisco",
  "Uber",
  "Airbnb",
  "Stripe",
  "Slack",
  "Zoom",
  "Figma",
  "Notion",
  "Atlassian",
  "Shopify",
  "Stripe",
  "Square",
  "PayPal",
  "Twitter",
  "LinkedIn",
  "GitHub",
  "GitLab",
  "Spotify",
  "TikTok",
  "Discord",
  "Twitch",
  "Roblox",
  "Snap",
  "Pinterest",
  "Reddit",
  "Quora",
  "Medium",
  "Substack",
  "Dropbox",
  "Box",
  "OneDrive",
  "AWS",
  "Azure",
  "Google Cloud",
  "Vercel",
  "Netlify",
  "Heroku",
  "DigitalOcean",
  "Linode",
  "Vultr",
  "Hetzner",
].sort();

export const COMMON_UNIVERSITIES = [
  "Harvard University",
  "Stanford University",
  "MIT",
  "Cambridge University",
  "Oxford University",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "Duke University",
  "Northwestern University",
  "University of Michigan",
  "UCLA",
  "UC Berkeley",
  "Stanford",
  "Carnegie Mellon University",
  "CalTech",
  "Northwestern",
  "University of Chicago",
  "Cornell University",
  "Georgia Tech",
  "University of Illinois",
  "University of Texas",
  "University of Wisconsin",
  "University of Washington",
  "University of Southern California",
  "Dartmouth College",
  "Brown University",
  "Rice University",
  "Emory University",
  "University of Florida",
  "Boston University",
  "New York University",
  "University of Massachusetts",
  "UCSD",
  "University of Minnesota",
  "University of Virginia",
  "University of Maryland",
  "Purdue University",
  "University of Arizona",
  "University of Colorado",
  "University of Oregon",
  "University of Pittsburgh",
  "University of Connecticut",
  "University of Rochester",
  "Imperial College London",
  "Swiss Federal Institute of Technology",
  "National University of Singapore",
  "University of Tokyo",
  "Australian National University",
  "University of Melbourne",
  "University of Sydney",
].sort();

export const COMMON_DEGREES = [
  "Bachelor of Science",
  "Bachelor of Arts",
  "Master of Science",
  "Master of Arts",
  "Master of Business Administration",
  "Doctor of Philosophy",
  "Doctor of Medicine",
  "Juris Doctor",
  "Bachelor of Engineering",
  "Master of Engineering",
  "Bachelor of Technology",
  "Associate Degree",
  "Diploma",
  "Certificate",
];

export const COMMON_FIELDS_OF_STUDY = [
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Web Development",
  "Mobile App Development",
  "Cloud Computing",
  "Business Administration",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "Human Resources",
  "Operations Management",
  "Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Medicine",
  "Psychology",
  "Education",
  "Law",
  "Political Science",
  "History",
  "Literature",
  "Philosophy",
  "Art",
  "Design",
  "Architecture",
  "Communications",
  "Journalism",
  "Environmental Science",
  "Statistics",
  "Biomedical Engineering",
  "Robotics",
  "Game Development",
  "Graphic Design",
  "UI/UX Design",
  "Product Management",
].sort();
